---

- name: djangoapp | Clone git repos
  git: >
    repo='https://github.com/emalloy/django-sample-app.git'
    dest={{ app_basedir }}
    version=dev
    accept_hostkey=yes
    update=yes
    force=yes

- name: djangoapp | install requirements
  pip: >
    requirements={{ app_basedir }}/requirements.txt
    state=present
